services:
  - type: background-worker
    name: smart-money-tracker
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HELIUS_API_KEY
        fromSecret: HELIUS_API_KEY
      - key: TELEGRAM_BOT_TOKEN
        fromSecret: TELEGRAM_BOT_TOKEN
      - key: TELEGRAM_USER_ID
        fromSecret: TELEGRAM_USER_ID
      - key: DATABASE_PATH
        value: ./data/tracker.db
    disk:
      name: smart-money-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1